#! /bin/bash
# This is the DagOn launcher script

code=0
if command -v python &>/dev/null; then
PYTHON=python
elif command -v python3 &>/dev/null; then
PYTHON=python3
else
 echo "Python is not available, please install Python to use DynoStore"
 exit 1
fi
if $PYTHON -c "import dynostore" &>/dev/null; then
 echo "DynoStore is installed"
else
 echo "DynoStore is not installed, installing..."
pip install git+https://github.com/dynostore/dynostore-client
 fi
echo 
 echo "************************************"
 echo 
# Change the current directory to the working directory
cd /tmp//1753368364877-A
if [ $? -ne 0 ]; then code=1; fi 

# Start staging in



# Invoke the command
mkdir output;hostname > output/f1.txt |tee /tmp//1753368364877-A/.dagon/stdout.txt
if [ $? -ne 0 ]; then code=1; fi

# Perform post process
echo "Pushing data to DynoStore server 13.49.70.153:8095"
dynostore --server 13.49.70.153:8095 put /tmp//1753368364877-A --recursive --catalog=1753368364877-A
exit $code